spring:
  application:
    name: calculator-service
  profiles:
    active: default
  aop:
    auto: true
    proxy-target-class: false

server:
  port: 8080

opentracing:
  jaeger:
    enabled: true
    service-name: ${spring.application.name}
    http-sender:
      url: http://localhost:14268/api/traces
    log-spans: true


#feature-flag.ccc-jaeger.tracing.enabled: true
feature-flag:
  ccc-jaeger:
    tracing:
      enabled: true

logging:
  level:
    org.example.metrics.common: DEBUG
